# Generated by Django 2.0.5 on 2018-08-14 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loansApp', '0002_loan_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='state',
            field=models.CharField(choices=[('A', 'Aceptado'), ('R', 'Rechazado'), ('P', 'Pendiente'), ('L', 'Perdido'), ('E', 'Recibido')], default='P', max_length=1, verbose_name='Estado'),
        ),
    ]
