# Generated by Django 2.0.5 on 2018-08-16 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loansApp', '0003_auto_20180814_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='article',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='user',
        ),
        migrations.DeleteModel(
            name='Loan',
        ),
    ]
