# Generated by Django 2.0.5 on 2018-08-16 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservationsApp', '0002_auto_20180814_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='space',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='user',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
