# Generated by Django 2.1 on 2018-08-20 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spacesApp', '0003_merge_20180820_1623'),
        ('spacesApp', '0003_merge_20180820_1502'),
    ]

    operations = [
    ]
