# Generated by Django 2.0.5 on 2018-08-21 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articleReservationsApp', '0003_auto_20180820_1804'),
        ('articleReservationsApp', '0002_auto_20180820_1853'),
        ('articleReservationsApp', '0002_auto_20180820_1912'),
    ]

    operations = [
    ]
