# Generated by Django 2.0.5 on 2018-08-20 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20180814_1633'),
        ('mainApp', '0002_auto_20180808_1701'),
    ]

    operations = [
    ]
