# Generated by Django 2.1 on 2018-08-20 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articlesApp', '0002_auto_20180801_1714'),
        ('articlesApp', '0002_auto_20180814_1633'),
    ]

    operations = [
    ]
