# Generated by Django 2.0.5 on 2018-08-20 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceReservationsApp', '0002_auto_20180820_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='spacereservation',
            name='finish_state',
            field=models.CharField(choices=[('L', 'Perdido'), ('E', 'Recibido'), ('I', 'Indefinido')], default='I', max_length=1, verbose_name='Estado de finalización'),
        ),
        migrations.AlterField(
            model_name='spacereservation',
            name='state',
            field=models.CharField(choices=[('A', 'Aceptado'), ('R', 'Rechazado'), ('P', 'Pendiente')], default='P', max_length=1, verbose_name='Estado'),
        ),
    ]
